apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.example.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - worker-deployment.yaml
  - worker-metrics-service.yaml
  - outbox-worker-deployment.yaml
  - outbox-worker-metrics-service.yaml
