apiVersion: apps/v1
kind: Deployment
metadata:
  name: minishop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minishop-api
  template:
    metadata:
      labels:
        app: minishop-api
    spec:
      containers:
        - name: api
          image: minishop-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: API_PORT
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: POSTGRES_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: REDIS_URL
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: KAFKA_BROKER

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_SERVICE_NAME
              value: "minishop-api"
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: minishop-config
                  key: OTEL_METRICS_EXPORTER

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: minishop-secrets
                  key: JWT_SECRET

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
