export const ORDER_STATUS = {
  PENDING: 'PEDIDO_PENDENTE',
  CONFIRMED: 'PEDIDO_CONFIRMADO',
  CANCELED: 'PEDIDO_CANCELADO',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'PAGAMENTO_PENDENTE',
  PENDING_VERIFICATION: 'PAGAMENTO_PENDENTE_VERIFICAÇÃO',
  CONFIRMED: 'PAGAMENTO_CONFIRMADO',
  FAILED: 'PAGAMENTO_FALHOU',
  RECONCILIATION_NEEDED: 'RECONCILIAÇÃO_NECESSÁRIA',
} as const;
