export const PAYMENT_STATUS = {
  PENDING: 'PAGAMENTO_PENDENTE',
  PENDING_VERIFICATION: 'PAGAMENTO_PENDENTE_VERIFICAÇÃO',
  CONFIRMED: 'PAGAMENTO_CONFIRMADO',
  FAILED: 'PAGAMENTO_FALHOU',
  RECONCILIATION_NEEDED: 'RECONCILIAÇÃO_NECESSÁRIA',
} as const;

export type PaymentStatus =
  (typeof PAYMENT_STATUS)[keyof typeof PAYMENT_STATUS];
